let init_data = {
    locations: [
        {
            name: "Alberta",
            img: "",
            line: "",
        },
        {
            name: "Arizona",
            img: "",
            line: "",
        },
        {
            name: "Australia",
            img: "",
            line: "",
        },
        {
            name: "Azerbaijan",
            img: "",
            line: "",
        },
        {
            name: "Belize",
            img: "",
            line: "",
        },
        {
            name: "Bhutan",
            img: "",
            line: "",
        },
        {
            name: "Bolivia",
            img: "",
            line: "",
        },
        {
            name: "Brazil",
            img: "",
            line: "",
        },
        {
            name: "California",
            img: "",
            line: "",
        },
        {
            name: "Cambodia",
            img: "",
            line: "",
        },
        {
            name: "Chile",
            img: "",
            line: "",
        },
        {
            name: "China",
            img: "",
            line: "",
        },
        {
            name: "Costa Rica",
            img: "",
            line: "",
        },
        {
            name: "Ecuador",
            img: "",
            line: "",
        },
        {
            name: "Egypt",
            img: "",
            line: "",
        },
        {
            name: "Germany",
            img: "",
            line: "",
        },
        {
            name: "Guatemala",
            img: "",
            line: "",
        },
        {
            name: "Hawaii",
            img: "",
            line: "",
        },
        {
            name: "Hong Kong",
            img: "",
            line: "",
        },
        {
            name: "Iceland",
            img: "",
            line: "",
        },
        {
            name: "India",
            img: "",
            line: "",
        },
        {
            name: "Indonesia",
            img: "",
            line: "",
        },
        {
            name: "Ireland",
            img: "",
            line: "",
        },
        {
            name: "Israel",
            img: "",
            line: "",
        },
        {
            name: "Italy",
            img: "",
            line: "",
        },
        {
            name: "Japan",
            img: "",
            line: "",
        },
        {
            name: "Jordan",
            img: "",
            line: "",
        },
        {
            name: "Louisiana",
            img: "",
            line: "",
        },
        {
            name: "Macau",
            img: "",
            line: "",
        },
        {
            name: "Mexico",
            img: "",
            line: "",
        },
        {
            name: "Morocco",
            img: "",
            line: "",
        },
        {
            name: "Nepal",
            img: "",
            line: "",
        },
        {
            name: "New York",
            img: "",
            line: "",
        },
        {
            name: "New Zealand",
            img: "",
            line: "",
        },
        {
            name: "Norway",
            img: "",
            line: "",
        },
        {
            name: "Nova Scotia",
            img: "",
            line: "",
        },
        {
            name: "Palau",
            img: "",
            line: "",
        },
        {
            name: "Peru",
            img: "",
            line: "",
        },
        {
            name: "Rhode Island",
            img: "",
            line: "",
        },
        {
            name: "Russia",
            img: "",
            line: "",
        },
        {
            name: "Scotland",
            img: "",
            line: "",
        },
        {
            name: "Singapore",
            img: "",
            line: "",
        },
        {
            name: "South Africa",
            img: "",
            line: "",
        },
        {
            name: "Sri Lanka",
            img: "",
            line: "",
        },
        {
            name: "Sweden",
            img: "",
            line: "",
        },
        {
            name: "Switzerland",
            img: "",
            line: "",
        },
        {
            name: "Taiwan",
            img: "",
            line: "",
        },
        {
            name: "Tanzania",
            img: "",
            line: "",
        },
        {
            name: "Thailand",
            img: "",
            line: "",
        },
        {
            name: "Turkey",
            img: "",
            line: "",
        },
        {
            name: "U.A.E.",
            img: "",
            line: "",
        },
        {
            name: "UK",
            img: "",
            line: "",
        },
        {
            name: "Uganda",
            img: "",
            line: "",
        },
        {
            name: "Utah",
            img: "",
            line: "",
        },
        {
            name: "Venezuela",
            img: "",
            line: "",
        },
        {
            name: "Vietnam",
            img: "",
            line: "",
        },
        {
            name: "Wisconsin",
            img: "",
            line: "",
        },
        {
            name: "Zambia",
            img: "",
            line: "",
        }
    ],
    activities: [
        {
            name: "Angel's Falls",
            location: "Venezuela",
            region: "South America",
            img: "https://d36tnp772eyphs.cloudfront.net/blogs/1/2014/05/Angel-Falls.jpg",
            notes: "Best view is from San Lucas",
            type: "Natural Wonders",
            season: "Spring",
            cost: 0,
            completed: false,
        },
        {
            name: "Angel's Landing",
            location: "Utah",
            region: "North America West",
            img: "https://images.theoutbound.com/contents/107088/assets/1449712939026?&fit=crop&w=970&h=550&auto=format&dpr=2&q=60",
            notes: "https://www.earthtrekkers.com/hiking/",
            type: "Hike",
            season: "Spring",
            cost: 0,
            completed: true,
        },
        {
            name: "Angkor Wat",
            location: "Cambodia",
            region: "Southeast Asia",
            img: "https://afar-production.imgix.net/uploads/images/post_images/images/VpVf8AwUKK/original_799b75adc253556f1994e1eba0ea6586.jpg?1509371577?ixlib=rails-0.3.0&auto=format%2Ccompress&crop=top&fit=crop&h=306&q=80&w=409",
            notes: "Optional excursion to visit some monkeys",
            type: "Ancient Ruins",
            season: "Spring",
            cost: 10,
            completed: false,
        },
        {
            name: "Calgary Stampede",
            location: "Alberta",
            region: "North America West",
            img: "https://www.calgarystampede.com/sites/default/files/cowboys-bucking-horse-rodeo-granstand-arena.jpg",
            notes: "Stay with bishop Bevans family when you go",
            type: "Music/Cultural Festival",
            season: "Summer",
            cost: 30,
            completed: true,
        },
        {
            name: "Carnaval",
            location: "Brazil",
            region: "South America",
            img: "https://img.buzzfeed.com/buzzfeed-static/static/2013-10/enhanced/webdr06/28/17/enhanced-buzz-7382-1382996324-20.jpg?downsize=800:*&output-format=auto&output-quality=auto",
            notes: "parades happen on first, third, and last day",
            type: "Music/Cultural Festival",
            season: "Spring",
            cost: 0,
            completed: false,
        },
        {
            name: "Carnevale",
            location: "Italy",
            region: "Europe",
            img: "https://img.buzzfeed.com/buzzfeed-static/static/2013-10/enhanced/webdr06/28/16/enhanced-buzz-orig-28081-1382993620-9.jpg?downsize=800:*&output-format=auto&output-quality=auto",
            notes: "masks are pretty ubiquitous",
            type: "Music/Cultural Festival",
            season: "Summer",
            cost: 20,
            completed: true,
        },
        {
            name: "Cliffs of Moher",
            location: "Ireland",
            region: "Europe",
            img: "https://d36tnp772eyphs.cloudfront.net/blogs/1/2014/05/cliffs-of-moher.jpg",
            notes: "Super iconic view",
            type: "Natural Wonders",
            season: "Spring",
            cost: 0,
            completed: true,
        },
        {
            name: "Dead Sea",
            location: "Israel",
            region: "Middle East",
            img: "https://d36tnp772eyphs.cloudfront.net/blogs/1/2014/05/View-of-Dead-Sea.jpg",
            notes: "Jordan side is less crowded",
            type: "Natural Wonders",
            season: "Spring",
            cost: 5,
            completed: false,
        },
        {
            name: "Desmond Castle",
            location: "Ireland",
            region: "Europe",
            img: "https://afar-production.imgix.net/uploads/images/post_images/images/jGKJBkk5xr/original_open-uri20130309-27217-18t3r7e?1383806529?ixlib=rails-0.3.0&auto=format%2Ccompress&crop=top&fit=crop&h=306&q=80&w=409",
            notes: "Can take tour bus or hike out",
            type: "Ancient Ruins",
            season: "Summer",
            cost: 0,
            completed: true,
        },
        {
            name: "Dio de los Muertos",
            location: "Mexico",
            region: "Central America",
            img: "https://img.buzzfeed.com/buzzfeed-static/static/2013-10/enhanced/webdr06/28/18/enhanced-buzz-16273-1383000025-20.jpg?downsize=800:*&output-format=auto&output-quality=auto",
            notes: "Bring Curtis as a translator",
            type: "Music/Cultural Festival",
            season: "Fall",
            cost: 0,
            completed: true,
        },
        {
            name: "Dumpling Festival",
            location: "Hong Kong",
            region: "East Asia",
            img: "https://img.traveltriangle.com/blog/wp-content/tr:w-700,h-400/uploads/2017/10/Dumpling-Festival.jpg",
            notes: "https://traveltriangle.com/blog/food-festivals-around-the-world/",
            type: "Food/Cooking",
            season: "Summer",
            cost: 30,
            completed: true,
        },
        {
            name: "Everest Base Camp",
            location: "Nepal",
            region: "South Asia",
            img: "https://d36tnp772eyphs.cloudfront.net/blogs/1/2014/05/Ama-Dablam-Everest-region-Himalaya-Nepal.jpg",
            notes: "11 Day Hike",
            type: "Hike",
            season: "Summer",
            cost: 1600,
            completed: false,
        },
        {
            name: "Fimmvörðuháls",
            location: "Iceland",
            region: "Europe",
            img: "https://d3hne3c382ip58.cloudfront.net/files/uploads/bookmundi/resized/cmsfeatured/fimmvorduhals-trekking-trail-1505808729-785X440.jpg",
            notes: "https://www.earthtrekkers.com/hiking/",
            type: "Hike",
            season: "Summer",
            cost: 0,
            completed: false,
        },
        {
            name: "Foodies Festival",
            location: "UK",
            region: "Europe",
            img: "https://img.traveltriangle.com/blog/wp-content/tr:w-700,h-400/uploads/2019/07/Foodies-Festival1.jpg",
            notes: "Focuses on food and well being, held at multiple locations on different days",
            type: "Food/Cooking",
            season: "Summer",
            cost: 35,
            completed: true,
        },
        {
            name: "Galapagos Islands",
            location: "Ecuador",
            region: "South America",
            img: "https://d36tnp772eyphs.cloudfront.net/blogs/1/2014/05/Galapagos-Islands.jpg",
            notes: "Cheaper to fly into Quito first",
            type: "Natural Wonders",
            season: "Winter",
            cost: 90,
            completed: false,
        },
        {
            name: "Giant's Causeway",
            location: "Ireland",
            region: "Europe",
            img: "https://d36tnp772eyphs.cloudfront.net/blogs/1/2014/05/Giants-Causeway-Antrim-Northern-Ireland.jpg",
            notes: "Check pinterest for fun picture ideas",
            type: "Natural Wonders",
            season: "Spring",
            cost: 8,
            completed: true,
        },
        {
            name: "Gorilla Trekking",
            location: "Uganda",
            region: "Sub-Saharan Africa",
            img: "https://www.rwandagorilla.com/wp-content/uploads/2019/11/Solo-gorilla-Trekking-Tour.jpg",
            notes: "only spend about one hour with gorillas, but all reviewers said it was worth it",
            type: "High Adventure",
            season: "Spring",
            cost: 120,
            completed: false,
        },
        {
            name: "Grand Canyon",
            location: "Arizona",
            region: "North America West",
            img: "https://d36tnp772eyphs.cloudfront.net/blogs/1/2014/05/View-over-the-south-and-north-rim-part-in-grand-canyon.jpg",
            notes: "rim to rim hikes are less crowded",
            type: "Natural Wonders",
            season: "Fall",
            cost: 0,
            completed: true,
        },
        {
            name: "Great Barrier Reef",
            location: "Australia",
            region: "Australia/Oceania",
            img: "https://d36tnp772eyphs.cloudfront.net/blogs/1/2014/05/Great-Barrier-Reef-in-Queensland-Australia.jpg",
            notes: "Scuba diving also available",
            type: "Natural Wonders",
            season: "Summer",
            cost: 39,
            completed: false,
        },
        {
            name: "Great Wall of China",
            location: "China",
            region: "East Asia",
            img: "https://cdn.britannica.com/82/94382-050-20CF23DB/Great-Wall-of-China-Beijing.jpg",
            notes: "Hike from Tianmenkou to Jiangxi",
            type: "Ancient Ruins",
            season: "Spring",
            cost: 0,
            completed: true,
        },
        {
            name: "Ha Long Bay",
            location: "Vietnam",
            region: "Southeast Asia",
            img: "https://bucketlistjourney.net/wp-content/uploads/2015/02/IMG_4446-copy.jpg",
            notes: "Helicopter or airplane tours are the best way to see it",
            type: "Natural Wonders",
            season: "Spring",
            cost: 0,
            completed: false,
        },
        {
            name: "Half Dome",
            location: "California",
            region: "North America West",
            img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Half_Dome_from_Glacier_Point%2C_Yosemite_NP_-_Diliff.jpg/405px-Half_Dome_from_Glacier_Point%2C_Yosemite_NP_-_Diliff.jpg",
            notes: "Permit needed",
            type: "Hike",
            season: "Summer",
            cost: 15,
            completed: true,
        },
        {
            name: "Harbor of Rio de Janeiro",
            location: "Brazil",
            region: "South America",
            img: "https://d36tnp772eyphs.cloudfront.net/blogs/1/2014/05/Rio-de-Janeiro-Brazil.jpg",
            notes: "See from giant Jesus statue",
            type: "Natural Wonders",
            season: "Summer",
            cost: 0,
            completed: false,
        },
        {
            name: "Holi",
            location: "India",
            region: "South Asia",
            img: "https://img.buzzfeed.com/buzzfeed-static/static/2013-10/enhanced/webdr03/28/16/enhanced-buzz-orig-4087-1382993227-14.jpg?downsize=700%3A%2A&output-quality=auto&output-format=auto",
            notes: "kolkata has biggest celebration",
            type: "Music/Cultural Festival",
            season: "Spring",
            cost: 0,
            completed: true,
        },
        {
            name: "Inca Trail",
            location: "Peru",
            region: "South America",
            img: "https://lp-cms-production.imgix.net/features/2012/05/Incatrail1_peru-ad42580ed5d9.jpg?auto=format&fit=crop&q=40&sharp=10&vib=20&ixlib=react-8.6.4&w=1946",
            notes: "Takes ~4 days",
            type: "Hike",
            season: "Fall",
            cost: 200,
            completed: false,
        },
        {
            name: "Isle of Skye",
            location: "Scotland",
            region: "Europe",
            img: "https://s27363.pcdn.co/wp-content/uploads/2016/09/Isle-of-Skye-Itinerary-Photo.jpg.optimal.jpg",
            notes: "https://www.earthtrekkers.com/hiking/",
            type: "Hike",
            season: "Summer",
            cost: 0,
            completed: false,
        },
        {
            name: "Jaguar Cave Zip-lining",
            location: "Belize",
            region: "Central America",
            img: "https://files.tripstodiscover.com/files/2017/04/jaguar-cave.jpg",
            notes: "Jungle views",
            type: "High Adventure",
            season: "Fall",
            cost: 50,
            completed: false,
        },
        {
            name: "Kayaking in Svalbard",
            location: "Norway",
            region: "Europe",
            img: "https://images.rove.me/w_1920,q_85/r29mhigr99ifgqxcxqkk/svalbard-kayaking-by-glaciers.jpg",
            notes: "Bearded seal colony in region",
            type: "High Adventure",
            season: "Spring",
            cost: 40,
            completed: false,
        },
        {
            name: "Kjeragbolten",
            location: "Norway",
            region: "Europe",
            img: "https://s27363.pcdn.co/wp-content/uploads/2016/03/Kjeragbolten.jpg.optimal.jpg",
            notes: "Huge Boulder wedged between two cliff faces",
            type: "Hike",
            season: "Summer",
            cost: 0,
            completed: false,
        },
        {
            name: "Komodo Island",
            location: "Indonesia",
            region: "Southeast Asia",
            img: "https://www.sailbali.com/wp-content/uploads/2018/04/komodo-island-2.jpg",
            notes: "Komodo dragons and pink sand beaches",
            type: "Natural Wonders",
            season: "Fall",
            cost: 60,
            completed: false,
        },
        {
            name: "Landmannaugar",
            location: "Iceland",
            region: "Europe",
            img: "https://www.extremeiceland.is/media/12442/landmannalaugar-35.jpg?anchor=center&amp;mode=crop&amp;quality=80&amp;width=837&amp;height=556&amp;rnd=131957489260000000",
            notes: "https://www.earthtrekkers.com/hiking/",
            type: "Hike",
            season: "Summer",
            cost: 0,
            completed: false,
        },
        {
            name: "Love Valley",
            location: "Turkey",
            region: "Middle East",
            img: "https://4.bp.blogspot.com/-QTLcdZ1EKDM/T6_-oOnjORI/AAAAAAAAUEg/Yds8vSqEmDI/s640/love+valley+goreme+turkey+1.jpg",
            notes: "Euphemistic name for… weird shaped rocks",
            type: "Hike",
            season: "Fall",
            cost: 0,
            completed: false,
        },
        {
            name: "Machu Picchu",
            location: "Peru",
            region: "South America",
            img: "https://afar-production.imgix.net/uploads/images/post_images/images/uTVl8rT7Dl/original_dd2fdf2d9354b292554042032f8033eb?1438137756?ixlib=rails-0.3.0&auto=format%2Ccompress&crop=top&fit=crop&h=306&q=80&w=409",
            notes: "Ask Anne about tour groups",
            type: "Ancient Ruins",
            season: "Winter",
            cost: 25,
            completed: true,
        },
        {
            name: "Mardi Gras",
            location: "Louisiana",
            region: "North America East",
            img: "https://img.buzzfeed.com/buzzfeed-static/static/2013-10/enhanced/webdr01/28/17/enhanced-buzz-orig-9463-1382994988-46.jpg?downsize=800:*&output-format=auto&output-quality=auto",
            notes: "fly in at least two days before",
            type: "Music/Cultural Festival",
            season: "Spring",
            cost: 0,
            completed: true,
        },
        {
            name: "Mario Kart",
            location: "Japan",
            region: "East Asia",
            img: "https://www.tokyoweekender.com/wp-content/uploads/2016/03/mario-karting-in-tokyo-3.jpg",
            notes: "costume rental included",
            type: "High Adventure",
            season: "Spring",
            cost: 80,
            completed: true,
        },
        {
            name: "Maslenitsa Pancake Festival",
            location: "Russia",
            region: "Europe",
            img: "https://img.traveltriangle.com/blog/wp-content/tr:w-700,h-400/uploads/2019/11/Maslenitsa-Pancake-Festival-300x171.jpg",
            notes: "One of the cheeriest events in Russia",
            type: "Food/Cooking",
            season: "Winter",
            cost: 25,
            completed: false,
        },
        {
            name: "Matterhorn",
            location: "Switzerland",
            region: "Europe",
            img: "https://d36tnp772eyphs.cloudfront.net/blogs/1/2014/05/Zermatt-Switzerland.jpg",
            notes: "Hike is harder from the Italian side",
            type: "Natural Wonders",
            season: "Summer",
            cost: 0,
            completed: true,
        },
        {
            name: "Montezuma Castle",
            location: "Arizona",
            region: "North America West",
            img: "https://afar-production.imgix.net/uploads/images/post_images/images/8ASgtZqC5J/original_35a027323ba8bb9f1cb26776b8507ded?1438293910?ixlib=rails-0.3.0&auto=format%2Ccompress&crop=top&fit=crop&h=306&q=80&w=409",
            notes: "Misnamed, Montezume most likely never set foot here",
            type: "Ancient Ruins",
            season: "Spring",
            cost: 0,
            completed: true,
        },
        {
            name: "Mountain Bike the Grand Staircase",
            location: "Utah",
            region: "North America West",
            img: "https://westernspirit.com/wp-content/uploads/2018/02/Escalante_canyon-biker.jpg",
            notes: "Bike rentals nearby",
            type: "High Adventure",
            season: "Fall",
            cost: 15,
            completed: false,
        },
        {
            name: "Mt. Kilimanjaro",
            location: "Tanzania",
            region: "Sub-Saharan Africa",
            img: "https://d36tnp772eyphs.cloudfront.net/blogs/1/2014/05/Three-giraffe-on-Kilimanjaro.jpg",
            notes: "https://www.earthtrekkers.com/hiking/",
            type: "Hike",
            season: "Winter",
            cost: 0,
            completed: false,
        },
        {
            name: "Mud Volcanoes",
            location: "Azerbaijan",
            region: "Middle East",
            img: "https://d36tnp772eyphs.cloudfront.net/blogs/1/2014/05/Active-mud-volcanoes-in-Gobustan-desert-Azerbaijan.jpg",
            notes: "Don't go without a guide",
            type: "Natural Wonders",
            season: "Spring",
            cost: 15,
            completed: false,
        },
        {
            name: "National Street Food Festival",
            location: "India",
            region: "South Asia",
            img: "https://img.traveltriangle.com/blog/wp-content/tr:w-700,h-400/uploads/2017/10/National-Street-Food-Festival.jpg",
            notes: "https://traveltriangle.com/blog/food-festivals-around-the-world/",
            type: "Food/Cooking",
            season: "Spring",
            cost: 15,
            completed: false,
        },
        {
            name: "Newport Folk Festival",
            location: "Rhode Island",
            region: "North America East",
            img: "https://media.npr.org/assets/img/2019/07/22/gettyimages-1006709316_wide-ab9abc9a025d266833238b2cfa97f3a9190509cc-s800-c85.jpg",
            notes: "Biggest folk music festival",
            type: "Music/Cultural Festival",
            season: "Summer",
            cost: 39,
            completed: false,
        },
        {
            name: "Niagara Falls",
            location: "New York",
            region: "North America East",
            img: "https://www.niagarafallslive.com/wp-content/uploads/2017/08/opt-falls-background-1600x1000-244k.jpg",
            notes: "Canada's side is better :D",
            type: "Natural Wonders",
            season: "Spring",
            cost: 0,
            completed: true,
        },
        {
            name: "Night Safari",
            location: "Singapore",
            region: "Southeast Asia",
            img: "https://media.tacdn.com/media/attractions-splice-spp-674x446/06/75/89/b2.jpg",
            notes: "Beware tiger attacks",
            type: "High Adventure",
            season: "Summer",
            cost: 30,
            completed: true,
        },
        {
            name: "Northern Lights",
            location: "Iceland",
            region: "Europe",
            img: "https://d36tnp772eyphs.cloudfront.net/blogs/1/2014/05/Aurora-borealis-Norway.jpg",
            notes: "Can watch from a thermal hot spring",
            type: "Natural Wonders",
            season: "Winter",
            cost: 0,
            completed: false,
        },
        {
            name: "Oktoberfest",
            location: "Germany",
            region: "Europe",
            img: "https://img.traveltriangle.com/blog/wp-content/tr:w-700,h-400/uploads/2017/10/Oktoberfest.jpg",
            notes: "Lots of non-alcoholic options",
            type: "Food/Cooking",
            season: "Fall",
            cost: 45,
            completed: true,
        },
        {
            name: "Paragliding in Geneva",
            location: "Switzerland",
            region: "Europe",
            img: "https://rafting.ch/wp-content/uploads/2017/06/Parapente_Saleve_Geneve_2_EN.jpg",
            notes: "Cheapest options in spring",
            type: "High Adventure",
            season: "Spring",
            cost: 80,
            completed: true,
        },
        {
            name: "Paricutin",
            location: "Mexico",
            region: "Central America",
            img: "https://d36tnp772eyphs.cloudfront.net/blogs/1/2014/05/Paricutin-Volcano-in-Michoacan-Mexico.jpg",
            notes: "Almost perfectly conical volcano",
            type: "Natural Wonders",
            season: "Spring",
            cost: 0,
            completed: false,
        },
        {
            name: "Petra",
            location: "Jordan",
            region: "Middle East",
            img: "https://bucketlistjourney.net/wp-content/uploads/2016/06/IMG_0661-copy.jpg",
            notes: "Spend night in Wadi Rum desert",
            type: "Ancient Ruins",
            season: "Spring",
            cost: 29,
            completed: false,
        },
        {
            name: "Pingxi Lantern Festival",
            location: "Taiwan",
            region: "East Asia",
            img: "https://img.buzzfeed.com/buzzfeed-static/static/2013-10/enhanced/webdr06/29/14/enhanced-buzz-orig-4866-1383070613-8.jpg?downsize=800:*&output-format=auto&output-quality=auto",
            notes: "best view is from nearby national park",
            type: "Music/Cultural Festival",
            season: "Summer",
            cost: 16,
            completed: true,
        },
        {
            name: "PizzaFest",
            location: "Italy",
            region: "Europe",
            img: "https://img.traveltriangle.com/blog/wp-content/tr:w-700,h-400/uploads/2017/10/Pizzafest.jpg",
            notes: "https://traveltriangle.com/blog/food-festivals-around-the-world/",
            type: "Food/Cooking",
            season: "Winter",
            cost: 40,
            completed: true,
        },
        {
            name: "Pompeii",
            location: "Italy",
            region: "Europe",
            img: "https://afar-production.imgix.net/uploads/images/post_images/images/Q1gd79jAcn/original_C_Pompeii_RM_YW8-2751465.jpg?1506706575?ixlib=rails-0.3.0&auto=format%2Ccompress&crop=top&fit=crop&h=306&q=80&w=409",
            notes: "Don't go during the summer, you'll get heatstroke",
            type: "Ancient Ruins",
            season: "Winter",
            cost: 18,
            completed: true,
        },
        {
            name: "Prambanan",
            location: "Indonesia",
            region: "Southeast Asia",
            img: "https://afar-production.imgix.net/uploads/images/post_images/images/brSCwghVCA/original_open-uri20121029-6090-47z6ar?1383798318?ixlib=rails-0.3.0&auto=format%2Ccompress&crop=top&fit=crop&h=306&q=80&w=409",
            notes: "Watch the sunrise from here",
            type: "Ancient Ruins",
            season: "Summer",
            cost: 0,
            completed: false,
        },
        {
            name: "Pyramids of Giza",
            location: "Egypt",
            region: "North Africa",
            img: "https://cdn.britannica.com/82/94382-050-20CF23DB/Great-Wall-of-China-Beijing.jpg",
            notes: "early in the morning is best bet to avoid crowds",
            type: "Ancient Ruins",
            season: "Fall",
            cost: 15,
            completed: false,
        },
        {
            name: "Rafting Colorado River",
            location: "Arizona",
            region: "North America West",
            img: "https://media.deseretdigital.com/file/e8dfee6423?crop=top:0|left:0|width:620|height:520|gravity:Center&quality=55&interlace=none&resize=height:520&order=resize,crop&c=14&a=26227072",
            notes: "Several tours leave from Utah",
            type: "High Adventure",
            season: "Summer",
            cost: 60,
            completed: true,
        },
        {
            name: "Rapa Nui (Easter Island)",
            location: "Chile",
            region: "South America",
            img: "https://afar-production.imgix.net/uploads/images/post_images/images/oq2ocdTUvG/original_71779d31f5db3e50c04681bc73e752be?1438139630?ixlib=rails-0.3.0&auto=format%2Ccompress&crop=top&fit=crop&h=306&q=80&w=409",
            notes: "travel very restricted, watch for flight deals",
            type: "Ancient Ruins",
            season: "Fall",
            cost: 50,
            completed: false,
        },
        {
            name: "Rappel Victoria Falls",
            location: "Costa Rica",
            region: "Central America",
            img: "https://cdn1.vacationscostarica.com/crvacations/guide/things-to-do/adventure/costa-rica-adventure.jpg",
            notes: "Grippy shoes are a must",
            type: "High Adventure",
            season: "Winter",
            cost: 40,
            completed: false,
        },
        {
            name: "Safari",
            location: "Tanzania",
            region: "Sub-Saharan Africa",
            img: "https://bucketlistjourney.net/wp-content/uploads/2013/08/IMG_9706-800x533.jpg",
            notes: "Multiple options, longest leave out of tanzania",
            type: "High Adventure",
            season: "Fall",
            cost: 135,
            completed: false,
        },
        {
            name: "Salardi Uyuni Salt Flats",
            location: "Bolivia",
            region: "South America",
            img: "https://d36tnp772eyphs.cloudfront.net/blogs/1/2014/05/Salar-de-Uyuni-in-Bolivia.jpg",
            notes: "Allow 3-4 days",
            type: "Natural Wonders",
            season: "Fall",
            cost: 30,
            completed: false,
        },
        {
            name: "Salon du Chocolat",
            location: "Ecuador",
            region: "South America",
            img: "https://img.traveltriangle.com/blog/wp-content/tr:w-700,h-400/uploads/2017/10/Salon-du-Chocolat.jpg",
            notes: "Features food and fashion made of high school",
            type: "Food/Cooking",
            season: "Winter",
            cost: 30,
            completed: false,
        },
        {
            name: "Scuba diving in Alexandria",
            location: "Egypt",
            region: "North Africa",
            img: "https://lh3.googleusercontent.com/proxy/-vYAUO478DrGlx423N-q3uku_1Ee9i_Os-J5EOJhHz9YBDlNkyzJ2A-yBKrBfX02l3QzLRcpGt--ulCWFl09kM9kv82Vlyqtr-l5I17yYd78pzb3",
            notes: "Certification required",
            type: "High Adventure",
            season: "Fall",
            cost: 45,
            completed: false,
        },
        {
            name: "Sigiriya Rock",
            location: "Sri Lanka",
            region: "South Asia",
            img: "https://bucketlistjourney.net/wp-content/uploads/2014/11/IMG_5040.jpg",
            notes: "Former palace and terraced garden at top",
            type: "Ancient Ruins",
            season: "Winter",
            cost: 0,
            completed: false,
        },
        {
            name: "Sky diving in Dubai",
            location: "U.A.E.",
            region: "Middle East",
            img: "https://cdn.shortpixel.ai/client/q_glossy,ret_img,w_960/https://flyingthenest.tv/wp-content/uploads/2014/07/549083_10152313672103185_2064924292_n.jpg",
            notes: "Visa can take 3-4 months",
            type: "High Adventure",
            season: "Winter",
            cost: 150,
            completed: false,
        },
        {
            name: "Sleep in Ice Hotel",
            location: "Sweden",
            region: "Europe",
            img: "https://www.icehotel.com/sites/cb_icehotel/files/icehotel.jpg",
            notes: "There's also a carnival held in an ice building nearby",
            type: "High Adventure",
            season: "Winter",
            cost: 290,
            completed: false,
        },
        {
            name: "Snow and Ice Festival",
            location: "China",
            region: "East Asia",
            img: "https://img.buzzfeed.com/buzzfeed-static/static/2013-10/enhanced/webdr01/28/15/enhanced-buzz-32024-1382987995-10.jpg?downsize=700%3A%2A&output-quality=auto&output-format=auto",
            notes: "held in Harbin!",
            type: "Music/Cultural Festival",
            season: "Winter",
            cost: 25,
            completed: true,
        },
        {
            name: "Songkran Water Festival",
            location: "Thailand",
            region: "Southeast Asia",
            img: "https://img.buzzfeed.com/buzzfeed-static/static/2013-10/enhanced/webdr06/28/19/enhanced-buzz-orig-16918-1383002514-15.jpg?downsize=800:*&output-format=auto&output-quality=auto",
            notes: "bring a super soaker",
            type: "Music/Cultural Festival",
            season: "Summer",
            cost: 0,
            completed: false,
        },
        {
            name: "St. Mouritz Gourmet Festival",
            location: "Switzerland",
            region: "Europe",
            img: "https://img.traveltriangle.com/blog/wp-content/tr:w-700,h-400/uploads/2019/11/St.-Moritz-Gourmet-Festival-300x171.jpg",
            notes: "https://traveltriangle.com/blog/food-festivals-around-the-world/",
            type: "Food/Cooking",
            season: "Fall",
            cost: 80,
            completed: false,
        },
        {
            name: "St. Paul's Church",
            location: "Macau",
            region: "East Asia",
            img: "https://afar-production.imgix.net/uploads/images/post_images/images/e5aSoHbR5w/original_98551a30b807e6aa2276d08e4be0f1ae?1383790804?ixlib=rails-0.3.0&auto=format%2Ccompress&crop=top&fit=crop&h=306&q=80&w=409",
            notes: "Ferry runs from HK",
            type: "Ancient Ruins",
            season: "Fall",
            cost: 0,
            completed: true,
        },
        {
            name: "Stonehenge",
            location: "UK",
            region: "Europe",
            img: "https://www.history.com/.image/t_share/MTYyNzgwNDg4MzQyMTg1ODI1/topic-stonehenge-gettyimages-682586546.jpg",
            notes: "not on the way to anything",
            type: "Ancient Ruins",
            season: "Summer",
            cost: 0,
            completed: true,
        },
        {
            name: "Summerfest",
            location: "Wisconsin",
            region: "North America East",
            img: "https://www.summerfest.com/assets/images/blog/2018/070417-day-avd-38lg.jpg",
            notes: "Coincides with trip to see Curtis!",
            type: "Music/Cultural Festival",
            season: "Summer",
            cost: 60,
            completed: false,
        },
        {
            name: "Swim with Jellyfish",
            location: "Palau",
            region: "Australia/Oceania",
            img: "https://bucketlistjourney.net/wp-content/uploads/2013/10/jellyfish.jpg",
            notes: "still string, but it's too mild to feel",
            type: "High Adventure",
            season: "Summer",
            cost: 35,
            completed: true,
        },
        {
            name: "Swim with Whale Sharks-Cancun",
            location: "Mexico",
            region: "Central America",
            img: "https://bucketlistjourney.net/wp-content/uploads/2014/08/DSCN1261.jpg",
            notes: "Whale sharks are gentlest breed of shark",
            type: "High Adventure",
            season: "Fall",
            cost: 28,
            completed: false,
        },
        {
            name: "The Black Forest",
            location: "Germany",
            region: "Europe",
            img: "https://d36tnp772eyphs.cloudfront.net/blogs/1/2014/05/Black-Forest-Germany.jpg",
            notes: "Visit Petra while you're here",
            type: "Natural Wonders",
            season: "Summer",
            cost: 0,
            completed: true,
        },
        {
            name: "The Zion Narrows",
            location: "Utah",
            region: "North America West",
            img: "https://images.theoutbound.com/contents/118306/assets/1494553194161?&fit=crop&w=970&h=550&auto=format&dpr=2&q=60",
            notes: "https://www.earthtrekkers.com/hiking/",
            type: "Hike",
            season: "Spring",
            cost: 0,
            completed: true,
        },
        {
            name: "Tidal Bore Rafting",
            location: "Nova Scotia",
            region: "North America East",
            img: "https://d36tnp772eyphs.cloudfront.net/blogs/1/2014/05/Hopewell-Rocks.jpg",
            notes: "Bay of Fundy, check 36 hour book",
            type: "High Adventure",
            season: "Winter",
            cost: 35,
            completed: false,
        },
        {
            name: "Tiger's Nest",
            location: "Bhutan",
            region: "South Asia",
            img: "https://s27363.pcdn.co/wp-content/uploads/2017/02/Tigers-Nest-Hike.jpg.optimal.jpg",
            notes: "900M Ascent, Bhutan has daily tourist tax",
            type: "Hike",
            season: "Summer",
            cost: 500,
            completed: false,
        },
        {
            name: "Tikal",
            location: "Guatemala",
            region: "Central America",
            img: "https://afar-production.imgix.net/uploads/images/post_images/images/cLaucLy5vp/original_abef1cf83bf7b494960fb426d3222220?1383790961?ixlib=rails-0.3.0&auto=format%2Ccompress&crop=top&fit=crop&h=306&q=80&w=409",
            notes: "Near old star wars set",
            type: "Ancient Ruins",
            season: "Fall",
            cost: 0,
            completed: false,
        },
        {
            name: "Tongairiro Alpine Crossing",
            location: "New Zealand",
            region: "Australia/Oceania",
            img: "https://images.squarespace-cdn.com/content/v1/5a87961cbe42d637c54cab93/1536202119151-MEKWQ2RU9NT6LFG0JEX1/ke17ZwdGBToddI8pDm48kHJjM-Evnp5g-1kf5Yv15cUUqsxRUqqbr1mOJYKfIPR7LoDQ9mXPOjoJoqy81S2I8N_N4V1vUb5AoIIIbLZhVYxCRW4BPu10St3TBAUQYVKcpWKe3KzaCrFDKPR1a1Ob8xobjReaxMuaKtrvUDoDmPO9EsdBHei1w8jR6w0UZiby/Tongariro+Alpine+Crossing+Complete+Guide+New+Zealand%27s+Best+Day+Hike?format=2500w",
            notes: "Voted World's Best Day Hike",
            type: "Hike",
            season: "Fall",
            cost: 0,
            completed: false,
        },
        {
            name: "Trolltunga",
            location: "Norway",
            region: "Europe",
            img: "https://s27363.pcdn.co/wp-content/uploads/2016/01/Julie-Rivenbark-on-Trolltunga.jpg.optimal.jpg",
            notes: "https://www.earthtrekkers.com/hiking/",
            type: "Hike",
            season: "Summer",
            cost: 0,
            completed: false,
        },
        {
            name: "Uluru",
            location: "Australia",
            region: "Australia/Oceania",
            img: "https://d36tnp772eyphs.cloudfront.net/blogs/1/2014/05/Uluru.jpg",
            notes: "Plan out a day to get out and back",
            type: "Natural Wonders",
            season: "Fall",
            cost: 20,
            completed: false,
        },
        {
            name: "Up Helly Aa Fire Festival",
            location: "Scotland",
            region: "Europe",
            img: "https://img.buzzfeed.com/buzzfeed-static/static/2013-10/enhanced/webdr01/28/17/enhanced-buzz-orig-11556-1382995316-22.jpg?downsize=800:*&output-format=auto&output-quality=auto",
            notes: "includes burning an old viking ship",
            type: "Music/Cultural Festival",
            season: "Winter",
            cost: 0,
            completed: false,
        },
        {
            name: "Vegetarian Festival",
            location: "Thailand",
            region: "Southeast Asia",
            img: "https://img.traveltriangle.com/blog/wp-content/tr:w-700,h-400/uploads/2017/10/Vegetarian-Festival.jpg",
            notes: "https://traveltriangle.com/blog/food-festivals-around-the-world/",
            type: "Food/Cooking",
            season: "Summer",
            cost: 20,
            completed: false,
        },
        {
            name: "Victoria Falls",
            location: "Zambia",
            region: "Sub-Saharan Africa",
            img: "https://d36tnp772eyphs.cloudfront.net/blogs/1/2014/05/Bird-eye-view-of-the-Victoria-falls-waterfall-on-Zambezi-river.jpg",
            notes: "Sky diving also available as an option",
            type: "Natural Wonders",
            season: "Spring",
            cost: 10,
            completed: false,
        },
        {
            name: "Volubilis",
            location: "Morocco",
            region: "North Africa",
            img: "https://afar-production.imgix.net/uploads/images/post_images/images/HUj8HEtH1q/original_open-uri20121222-8798-15nv1k7?1383801184?ixlib=rails-0.3.0&auto=format%2Ccompress&crop=top&fit=crop&h=306&q=80&w=409",
            notes: "Roman ruins",
            type: "Ancient Ruins",
            season: "Fall",
            cost: 15,
            completed: false,
        },
        {
            name: "Wanderlust Yoga Festival",
            location: "Hawaii",
            region: "Australia/Oceania",
            img: "https://img.buzzfeed.com/buzzfeed-static/static/2013-10/enhanced/webdr06/29/14/enhanced-buzz-orig-12655-1383069799-40.jpg?downsize=800:*&output-format=auto&output-quality=auto",
            notes: "sells out quickly",
            type: "Music/Cultural Festival",
            season: "Fall",
            cost: 95,
            completed: true,
        },
        {
            name: "Zhangjiajie",
            location: "China",
            region: "East Asia",
            img: "https://d36tnp772eyphs.cloudfront.net/blogs/1/2014/05/Zhangjiajie.jpg",
            notes: "Part of where Avatar was shot",
            type: "Natural Wonders",
            season: "Fall",
            cost: 15,
            completed: true,
        },
        {
            name: "Zip2000 Sun City",
            location: "South Africa",
            region: "Sub-Saharan Africa",
            img: "https://files.tripstodiscover.com/files/2017/04/Sun-City-zip-line.jpg",
            notes: "Fastest zipline in the world",
            type: "High Adventure",
            season: "Spring",
            cost: 90,
            completed: false,
        }        
    ],
    activityTypes: [
        "All",
        "Ancient Ruins",
        "Food/Cooking",
        "High Adventure",
        "Hike",
        "Music/Cultural Festival",
        "Natural Wonders"        
    ],
    activitySeasons: [
        "All",
        "Spring",
        "Summer",
        "Autumn",
        "Winter"
    ],
    regions: [
        "All",
        "North America West",
        "North America East",
        "Central America",
        "South America",
        "Europe",
        "Sub-Saharan Africa",
        "North Africa",
        "Middle East",
        "South Asia",
        "Southeast Asia",
        "East Asia",
        "Australia/Oceania"
    ],
}
export default init_data;